// Configuración de Firebase
const firebaseConfig = {
    apiKey: "AIzaSyBrYA0_hCMoQD7CSH3BXTH4Gdwt_oYsVho",
    authDomain: "easy-language-learning-f.firebaseapp.com",
    databaseURL: "https://easy-language-learning-f-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "easy-language-learning-f",
    storageBucket: "easy-language-learning-f.firebasestorage.app",
    messagingSenderId: "883430389199",
    appId: "1:883430389199:web:9dfbfa5933fd756dda4eba",
    measurementId: "G-MS5V079QZ2"
};

// Inicializar Firebase
firebase.initializeApp(firebaseConfig);
const database = firebase.database();

// Lista de adverbios en formato JSON
const adverbs = [
    { french: "Actuellement", spanish: "Actualmente" },
    { french: "Assurément", spanish: "Seguramente/Definitivamente" },
    { french: "Autrement", spanish: "De otra manera/De otro modo" },
    { french: "Calmement", spanish: "Tranquilamente" },
    { french: "Certainement", spanish: "Ciertamente" },
    { french: "Clairement", spanish: "Claramente" },
    { french: "Complètement", spanish: "Completamente" },
    { french: "Couramment", spanish: "Con fluidez" },
    { french: "Doucement", spanish: "Suavemente/En silencio" },
    { french: "Également", spanish: "También/Igualmente" },
    { french: "Énormément", spanish: "Enormemente" },
    { french: "Facilement", spanish: "Fácilmente" },
    { french: "Fortement", spanish: "Fuertemente" },
    { french: "Franchement", spanish: "Francamente" },
    { french: "Fréquemment", spanish: "Frecuentemente" },
    { french: "Habituellement", spanish: "Usualmente" },
    { french: "Heureusement", spanish: "Afortunadamente" },
    { french: "Honnêtement", spanish: "Honestamente" },
    { french: "Joliment", spanish: "Bonitamente/Amablemente" },
    { french: "Largement", spanish: "Ampliamente/Bien" },
    { french: "Légèrement", spanish: "Ligeramente" },
    { french: "Lentement", spanish: "Lentamente" },
    { french: "Malheureusement", spanish: "Desafortunadamente" },
    { french: "Poliment", spanish: "Cortésmente" },
    { french: "Précisément", spanish: "Precisamente" },
    { french: "Probablement", spanish: "Probablemente" },
    { french: "Profondément", spanish: "Profundamente" },
    { french: "Rapidement", spanish: "Rápidamente" },
    { french: "Rarement", spanish: "Raramente" },
    { french: "Récemment", spanish: "Recientemente" },
    { french: "Seulement", spanish: "Solamente" },
    { french: "Suffisamment", spanish: "Suficientemente" },
    { french: "Sûrement", spanish: "Seguramente" },
    { french: "Tellement", spanish: "Tanto" },
    { french: "Vraiment", spanish: "Realmente/Verdaderamente" },
    { french: "À Côté", spanish: "Al lado" },
    { french: "À Droite", spanish: "A la derecha" },
    { french: "À Gauche", spanish: "A la izquierda" },
    { french: "À L’Intérieur", spanish: "En el interior" },
    { french: "D’Abord", spanish: "Primero/En primer lugar" },
    { french: "En Dehors De", spanish: "Fuera/Aparte de" },
    { french: "Au-Delà De", spanish: "Más allá de" },
    { french: "En Bas", spanish: "Abajo" },
    { french: "En Effet", spanish: "De hecho" },
    { french: "En Face", spanish: "Enfrente" },
    { french: "En Haut", spanish: "Arriba" },
    { french: "En Même Temps", spanish: "Al mismo tiempo" },
    { french: "En Revanche", spanish: "Sin embargo/En contraste" },
    { french: "Là-Bas", spanish: "Allá" },
    { french: "Là-Dedans", spanish: "Aquí dentro/Allí dentro" },
    { french: "Là-Dessus", spanish: "Aquí encima/Allí encima" },
    { french: "Lors De", spanish: "Durante" },
    { french: "Nulle Part", spanish: "En ninguna parte" },
    { french: "Par Contre", spanish: "Por el contrario" },
    { french: "Pas Du Tout", spanish: "Para nada" },
    { french: "Sans Doute", spanish: "Sin duda" },
    { french: "Ailleurs", spanish: "En otro lugar" },
    { french: "Ainsi", spanish: "Así" },
    { french: "Alors", spanish: "Entonces/Así/En ese momento" },
    { french: "Après", spanish: "Después" },
    { french: "Après-Demain", spanish: "Pasado mañana" },
    { french: "Aujourd’hui", spanish: "Hoy" },
    { french: "Assez", spanish: "Suficiente" },
    { french: "Avant-Hier", spanish: "Anteayer" },
    { french: "Aussi", spanish: "También" },
    { french: "Aussitôt", spanish: "Inmediatamente" },
    { french: "Autant", spanish: "Tanto" },
    { french: "Autrefois", spanish: "En el pasado" },
    { french: "Beaucoup (De)", spanish: "Mucho/Muchos" },
    { french: "Bien", spanish: "Bien" },
    { french: "Bientôt", spanish: "Pronto" },
    { french: "Cependant", spanish: "Sin embargo" },
    { french: "Certes", spanish: "Ciertamente/Por supuesto" },
    { french: "Ci-Dessous", spanish: "Abajo" },
    { french: "Combien (De)", spanish: "Cuánto/Cuántos" },
    { french: "Comment", spanish: "Cómo" },
    { french: "Davantage", spanish: "Más/Más tiempo" },
    { french: "Debout", spanish: "De pie/Levantado" },
    { french: "Dedans", spanish: "Dentro" },
    { french: "Déjà", spanish: "Ya" },
    { french: "Demain", spanish: "Mañana" },
    { french: "Depuis", spanish: "Desde" },
    { french: "Derrière", spanish: "Detrás" },
    { french: "Désormais", spanish: "De ahora en adelante" },
    { french: "Dessous", spanish: "Debajo" },
    { french: "Dessus", spanish: "Encima" },
    { french: "Devant", spanish: "Delante" },
    { french: "D’Habitude", spanish: "Usualmente" },
    { french: "Donc", spanish: "Por lo tanto/Así que" },
    { french: "Encore", spanish: "Otra vez/Todavía" },
    { french: "Enfin", spanish: "Finalmente" },
    { french: "Ensemble", spanish: "Juntos" },
    { french: "Ensuite", spanish: "Luego/Después" },
    { french: "Environ", spanish: "Aproximadamente" },
    { french: "Hélas", spanish: "Ay" },
    { french: "Hier", spanish: "Ayer" },
    { french: "Ici", spanish: "Aquí/Ahora" },
    { french: "Jadis", spanish: "Antiguamente" },
    { french: "Jamais", spanish: "Nunca/Jamás" },
    { french: "Là", spanish: "Allí" },
    { french: "Longtemps", spanish: "Mucho tiempo" },
    { french: "Loin", spanish: "Lejos" },
    { french: "Maintenant", spanish: "Ahora" },
    { french: "Mal", spanish: "Mal/Incorrectamente" },
    { french: "Mieux", spanish: "Mejor" },
    { french: "Moins", spanish: "Menos" },
    { french: "Néanmoins", spanish: "No obstante" },
    { french: "Où", spanish: "Dónde" },
    { french: "Parfois", spanish: "A veces" },
    { french: "Partout", spanish: "En todas partes" },
    { french: "Peu", spanish: "Poco" },
    { french: "Peut-être", spanish: "Quizás/Tal vez" },
    { french: "Plutôt", spanish: "Más bien/Bastante" },
    { french: "Presque", spanish: "Casi" },
    { french: "Probablement", spanish: "Probablemente" },
    { french: "Pourquoi", spanish: "Por qué" },
    { french: "Prudemment", spanish: "Prudentemente/Con cuidado" },
    { french: "Puis", spanish: "Luego/Después" },
    { french: "Quelquefois", spanish: "Algunas veces" },
    { french: "Rarement", spanish: "Raramente" },
    { french: "Récemment", spanish: "Recientemente" },
    { french: "Régulièrement", spanish: "Regularmente" },
    { french: "Relativement", spanish: "Relativamente" },
    { french: "Sans doute", spanish: "Sin duda" },
    { french: "Surtout", spanish: "Sobre todo/Principalmente" },
    { french: "Tard", spanish: "Tarde" },
    { french: "Tôt", spanish: "Temprano" },
    { french: "Toujours", spanish: "Siempre" },
    { french: "Tout", spanish: "Todo/Completamente" },
    { french: "Tout à coup", spanish: "De repente" },
    { french: "Tout de suite", spanish: "Enseguida/De inmediato" },
    { french: "Tout le temps", spanish: "Todo el tiempo" },
    { french: "Tout à fait", spanish: "Completamente/Totalmente" },
    { french: "Tout d’abord", spanish: "Antes que nada" },
    { french: "Tout de même", spanish: "Aun así" },
    { french: "Tout simplement", spanish: "Simplemente" },
    { french: "Vite", spanish: "Rápido/De prisa" } 
];


// Función para insertar los adverbios en la base de datos
function insertAdverbs() {
    const categoryRef = database.ref('WcT569oObqhffyalDvrREkeKoT22/categories/Adverbios');

    adverbs.forEach((adverb, index) => {
        const newAdverbRef = categoryRef.push(); // Genera una clave única para cada adverbio
        newAdverbRef.set({
            french: adverb.french,
            spanish: adverb.spanish
        })
        .then(() => {
            console.log(`Adverbio ${index + 1}: ${adverb.french} añadido correctamente.`);
        })
        .catch((error) => {
            console.error(`Error al añadir ${adverb.french}:`, error);
        });
    });
}
insertAdverbs();